//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kursovaya_Rabota_4
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// БазДан.
    /// </summary>
    // *** Start programmer edit section *** (БазДан CustomAttributes)

    // *** End programmer edit section *** (БазДан CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("БазДанE", new string[] {
            "СпрСтуд as \'Фио студента\'",
            "СпрСтуд.Фио as \'Фио студента\'",
            "СпрСтуд.СпрГруппа.Назв as \'Группа\'",
            "СпрСтуд.СпрДисциплина.Наименование as \'Дисиплина\'",
            "СпрМатериалы as \'Название материала\'",
            "СпрМатериалы.Наименование as \'Название материала\'",
            "СпрМатериалы.Вид as \'Вид материала\'"})]
    [MasterViewDefineAttribute("БазДанE", "СпрСтуд", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Фио студента")]
    [MasterViewDefineAttribute("БазДанE", "СпрМатериалы", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Название материала")]
    public class БазДан : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДата;
        
        private IIS.Kursovaya_Rabota_4.СпрМатериалы fСпрМатериалы;
        
        private IIS.Kursovaya_Rabota_4.СпрСтуд fСпрСтуд;
        
        private IIS.Kursovaya_Rabota_4.ПрикрепКн fПрикрепКн;
        
        // *** Start programmer edit section *** (БазДан CustomMembers)

        // *** End programmer edit section *** (БазДан CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (БазДан.Дата CustomAttributes)

        // *** End programmer edit section *** (БазДан.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (БазДан.Дата Get start)

                // *** End programmer edit section *** (БазДан.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (БазДан.Дата Get end)

                // *** End programmer edit section *** (БазДан.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (БазДан.Дата Set start)

                // *** End programmer edit section *** (БазДан.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (БазДан.Дата Set end)

                // *** End programmer edit section *** (БазДан.Дата Set end)
            }
        }
        
        /// <summary>
        /// БазДан.
        /// </summary>
        // *** Start programmer edit section *** (БазДан.СпрМатериалы CustomAttributes)

        // *** End programmer edit section *** (БазДан.СпрМатериалы CustomAttributes)
        [PropertyStorage(new string[] {
                "СпрМатериалы"})]
        [NotNull()]
        public virtual IIS.Kursovaya_Rabota_4.СпрМатериалы СпрМатериалы
        {
            get
            {
                // *** Start programmer edit section *** (БазДан.СпрМатериалы Get start)

                // *** End programmer edit section *** (БазДан.СпрМатериалы Get start)
                IIS.Kursovaya_Rabota_4.СпрМатериалы result = this.fСпрМатериалы;
                // *** Start programmer edit section *** (БазДан.СпрМатериалы Get end)

                // *** End programmer edit section *** (БазДан.СпрМатериалы Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (БазДан.СпрМатериалы Set start)

                // *** End programmer edit section *** (БазДан.СпрМатериалы Set start)
                this.fСпрМатериалы = value;
                // *** Start programmer edit section *** (БазДан.СпрМатериалы Set end)

                // *** End programmer edit section *** (БазДан.СпрМатериалы Set end)
            }
        }
        
        /// <summary>
        /// БазДан.
        /// </summary>
        // *** Start programmer edit section *** (БазДан.СпрСтуд CustomAttributes)

        // *** End programmer edit section *** (БазДан.СпрСтуд CustomAttributes)
        [PropertyStorage(new string[] {
                "СпрСтуд"})]
        [NotNull()]
        public virtual IIS.Kursovaya_Rabota_4.СпрСтуд СпрСтуд
        {
            get
            {
                // *** Start programmer edit section *** (БазДан.СпрСтуд Get start)

                // *** End programmer edit section *** (БазДан.СпрСтуд Get start)
                IIS.Kursovaya_Rabota_4.СпрСтуд result = this.fСпрСтуд;
                // *** Start programmer edit section *** (БазДан.СпрСтуд Get end)

                // *** End programmer edit section *** (БазДан.СпрСтуд Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (БазДан.СпрСтуд Set start)

                // *** End programmer edit section *** (БазДан.СпрСтуд Set start)
                this.fСпрСтуд = value;
                // *** Start programmer edit section *** (БазДан.СпрСтуд Set end)

                // *** End programmer edit section *** (БазДан.СпрСтуд Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Kursovaya_Rabota_4.ПрикрепКн.
        /// </summary>
        // *** Start programmer edit section *** (БазДан.ПрикрепКн CustomAttributes)

        // *** End programmer edit section *** (БазДан.ПрикрепКн CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "ПрикрепКн"})]
        public virtual IIS.Kursovaya_Rabota_4.ПрикрепКн ПрикрепКн
        {
            get
            {
                // *** Start programmer edit section *** (БазДан.ПрикрепКн Get start)

                // *** End programmer edit section *** (БазДан.ПрикрепКн Get start)
                IIS.Kursovaya_Rabota_4.ПрикрепКн result = this.fПрикрепКн;
                // *** Start programmer edit section *** (БазДан.ПрикрепКн Get end)

                // *** End programmer edit section *** (БазДан.ПрикрепКн Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (БазДан.ПрикрепКн Set start)

                // *** End programmer edit section *** (БазДан.ПрикрепКн Set start)
                this.fПрикрепКн = value;
                // *** Start programmer edit section *** (БазДан.ПрикрепКн Set end)

                // *** End programmer edit section *** (БазДан.ПрикрепКн Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "БазДанE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View БазДанE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("БазДанE", typeof(IIS.Kursovaya_Rabota_4.БазДан));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of БазДан.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfБазДан CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfБазДан CustomAttributes)
    public class DetailArrayOfБазДан : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Kursovaya_Rabota_4.DetailArrayOfБазДан members)

        // *** End programmer edit section *** (IIS.Kursovaya_Rabota_4.DetailArrayOfБазДан members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type БазДан by index.
        /// </summary>
        /// <summary>
        /// Adds object with type БазДан.
        /// </summary>
        public DetailArrayOfБазДан(IIS.Kursovaya_Rabota_4.ПрикрепКн fПрикрепКн) : 
                base(typeof(БазДан), ((ICSSoft.STORMNET.DataObject)(fПрикрепКн)))
        {
        }
        
        public IIS.Kursovaya_Rabota_4.БазДан this[int index]
        {
            get
            {
                return ((IIS.Kursovaya_Rabota_4.БазДан)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Kursovaya_Rabota_4.БазДан dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
