//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kursovaya_Rabota_4
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Вид.
    /// </summary>
    // *** Start programmer edit section *** (Вид CustomAttributes)

    // *** End programmer edit section *** (Вид CustomAttributes)
    public enum Вид
    {
        
        // *** Start programmer edit section *** (Вид.УчКн CustomAttributes)

        // *** End programmer edit section *** (Вид.УчКн CustomAttributes)
        [Caption("Учебная книга")]
        УчКн,
        
        // *** Start programmer edit section *** (Вид.Методичка CustomAttributes)

        // *** End programmer edit section *** (Вид.Методичка CustomAttributes)
        [Caption("Методичка")]
        Методичка,
    }
}
