//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kursovaya_Rabota_4
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Контр.
    /// </summary>
    // *** Start programmer edit section *** (Контр CustomAttributes)

    // *** End programmer edit section *** (Контр CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("КонтрE", new string[] {
            "СпрСтуд as \'Фио студента\'",
            "СпрСтуд.Фио as \'Фио студента\'",
            "СпрСтуд.СпрГруппа.Назв as \'Группа\'",
            "СпрСтуд.СпрДисциплина.Наименование as \'Дисциплина\'",
            "Статус as \'Статус прикрепления\'",
            "Просмотр as \'Статус просмотра\'"})]
    [MasterViewDefineAttribute("КонтрE", "СпрСтуд", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Фио студента")]
    public class Контр : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДата;
        
        private bool fПросмотр;
        
        private IIS.Kursovaya_Rabota_4.Статус fСтатус;
        
        private IIS.Kursovaya_Rabota_4.СпрСтуд fСпрСтуд;
        
        private IIS.Kursovaya_Rabota_4.Стат fСтат;
        
        // *** Start programmer edit section *** (Контр CustomMembers)

        // *** End programmer edit section *** (Контр CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (Контр.Дата CustomAttributes)

        // *** End programmer edit section *** (Контр.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (Контр.Дата Get start)

                // *** End programmer edit section *** (Контр.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (Контр.Дата Get end)

                // *** End programmer edit section *** (Контр.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Контр.Дата Set start)

                // *** End programmer edit section *** (Контр.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (Контр.Дата Set end)

                // *** End programmer edit section *** (Контр.Дата Set end)
            }
        }
        
        /// <summary>
        /// Просмотр.
        /// </summary>
        // *** Start programmer edit section *** (Контр.Просмотр CustomAttributes)

        // *** End programmer edit section *** (Контр.Просмотр CustomAttributes)
        public virtual bool Просмотр
        {
            get
            {
                // *** Start programmer edit section *** (Контр.Просмотр Get start)

                // *** End programmer edit section *** (Контр.Просмотр Get start)
                bool result = this.fПросмотр;
                // *** Start programmer edit section *** (Контр.Просмотр Get end)

                // *** End programmer edit section *** (Контр.Просмотр Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Контр.Просмотр Set start)

                // *** End programmer edit section *** (Контр.Просмотр Set start)
                this.fПросмотр = value;
                // *** Start programmer edit section *** (Контр.Просмотр Set end)

                // *** End programmer edit section *** (Контр.Просмотр Set end)
            }
        }
        
        /// <summary>
        /// Статус.
        /// </summary>
        // *** Start programmer edit section *** (Контр.Статус CustomAttributes)

        // *** End programmer edit section *** (Контр.Статус CustomAttributes)
        public virtual IIS.Kursovaya_Rabota_4.Статус Статус
        {
            get
            {
                // *** Start programmer edit section *** (Контр.Статус Get start)

                // *** End programmer edit section *** (Контр.Статус Get start)
                IIS.Kursovaya_Rabota_4.Статус result = this.fСтатус;
                // *** Start programmer edit section *** (Контр.Статус Get end)

                // *** End programmer edit section *** (Контр.Статус Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Контр.Статус Set start)

                // *** End programmer edit section *** (Контр.Статус Set start)
                this.fСтатус = value;
                // *** Start programmer edit section *** (Контр.Статус Set end)

                // *** End programmer edit section *** (Контр.Статус Set end)
            }
        }
        
        /// <summary>
        /// Контр.
        /// </summary>
        // *** Start programmer edit section *** (Контр.СпрСтуд CustomAttributes)

        // *** End programmer edit section *** (Контр.СпрСтуд CustomAttributes)
        [PropertyStorage(new string[] {
                "СпрСтуд"})]
        [NotNull()]
        public virtual IIS.Kursovaya_Rabota_4.СпрСтуд СпрСтуд
        {
            get
            {
                // *** Start programmer edit section *** (Контр.СпрСтуд Get start)

                // *** End programmer edit section *** (Контр.СпрСтуд Get start)
                IIS.Kursovaya_Rabota_4.СпрСтуд result = this.fСпрСтуд;
                // *** Start programmer edit section *** (Контр.СпрСтуд Get end)

                // *** End programmer edit section *** (Контр.СпрСтуд Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Контр.СпрСтуд Set start)

                // *** End programmer edit section *** (Контр.СпрСтуд Set start)
                this.fСпрСтуд = value;
                // *** Start programmer edit section *** (Контр.СпрСтуд Set end)

                // *** End programmer edit section *** (Контр.СпрСтуд Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Kursovaya_Rabota_4.Стат.
        /// </summary>
        // *** Start programmer edit section *** (Контр.Стат CustomAttributes)

        // *** End programmer edit section *** (Контр.Стат CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Стат"})]
        public virtual IIS.Kursovaya_Rabota_4.Стат Стат
        {
            get
            {
                // *** Start programmer edit section *** (Контр.Стат Get start)

                // *** End programmer edit section *** (Контр.Стат Get start)
                IIS.Kursovaya_Rabota_4.Стат result = this.fСтат;
                // *** Start programmer edit section *** (Контр.Стат Get end)

                // *** End programmer edit section *** (Контр.Стат Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Контр.Стат Set start)

                // *** End programmer edit section *** (Контр.Стат Set start)
                this.fСтат = value;
                // *** Start programmer edit section *** (Контр.Стат Set end)

                // *** End programmer edit section *** (Контр.Стат Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "КонтрE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КонтрE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КонтрE", typeof(IIS.Kursovaya_Rabota_4.Контр));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of Контр.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfКонтр CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfКонтр CustomAttributes)
    public class DetailArrayOfКонтр : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Kursovaya_Rabota_4.DetailArrayOfКонтр members)

        // *** End programmer edit section *** (IIS.Kursovaya_Rabota_4.DetailArrayOfКонтр members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type Контр by index.
        /// </summary>
        /// <summary>
        /// Adds object with type Контр.
        /// </summary>
        public DetailArrayOfКонтр(IIS.Kursovaya_Rabota_4.Стат fСтат) : 
                base(typeof(Контр), ((ICSSoft.STORMNET.DataObject)(fСтат)))
        {
        }
        
        public IIS.Kursovaya_Rabota_4.Контр this[int index]
        {
            get
            {
                return ((IIS.Kursovaya_Rabota_4.Контр)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Kursovaya_Rabota_4.Контр dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
