//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kursovaya_Rabota_4
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// МетМат.
    /// </summary>
    // *** Start programmer edit section *** (МетМат CustomAttributes)

    // *** End programmer edit section *** (МетМат CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("МетМатE", new string[] {
            "СпрМатериалы as \'Материал\'",
            "СпрМатериалы.Наименование as \'Материал\'",
            "СпрМатериалы.Вид as \'Вид материала\'",
            "СпрМатериалы.СпрДисциплина.Наименование as \'Дисциплина\'"})]
    [MasterViewDefineAttribute("МетМатE", "СпрМатериалы", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Материал")]
    public class МетМат : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДата;
        
        private IIS.Kursovaya_Rabota_4.СпрМатериалы fСпрМатериалы;
        
        private IIS.Kursovaya_Rabota_4.Просмотр fПросмотр;
        
        // *** Start programmer edit section *** (МетМат CustomMembers)

        // *** End programmer edit section *** (МетМат CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (МетМат.Дата CustomAttributes)

        // *** End programmer edit section *** (МетМат.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (МетМат.Дата Get start)

                // *** End programmer edit section *** (МетМат.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (МетМат.Дата Get end)

                // *** End programmer edit section *** (МетМат.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (МетМат.Дата Set start)

                // *** End programmer edit section *** (МетМат.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (МетМат.Дата Set end)

                // *** End programmer edit section *** (МетМат.Дата Set end)
            }
        }
        
        /// <summary>
        /// МетМат.
        /// </summary>
        // *** Start programmer edit section *** (МетМат.СпрМатериалы CustomAttributes)

        // *** End programmer edit section *** (МетМат.СпрМатериалы CustomAttributes)
        [PropertyStorage(new string[] {
                "СпрМатериалы"})]
        [NotNull()]
        public virtual IIS.Kursovaya_Rabota_4.СпрМатериалы СпрМатериалы
        {
            get
            {
                // *** Start programmer edit section *** (МетМат.СпрМатериалы Get start)

                // *** End programmer edit section *** (МетМат.СпрМатериалы Get start)
                IIS.Kursovaya_Rabota_4.СпрМатериалы result = this.fСпрМатериалы;
                // *** Start programmer edit section *** (МетМат.СпрМатериалы Get end)

                // *** End programmer edit section *** (МетМат.СпрМатериалы Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (МетМат.СпрМатериалы Set start)

                // *** End programmer edit section *** (МетМат.СпрМатериалы Set start)
                this.fСпрМатериалы = value;
                // *** Start programmer edit section *** (МетМат.СпрМатериалы Set end)

                // *** End programmer edit section *** (МетМат.СпрМатериалы Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Kursovaya_Rabota_4.Просмотр.
        /// </summary>
        // *** Start programmer edit section *** (МетМат.Просмотр CustomAttributes)

        // *** End programmer edit section *** (МетМат.Просмотр CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Просмотр"})]
        public virtual IIS.Kursovaya_Rabota_4.Просмотр Просмотр
        {
            get
            {
                // *** Start programmer edit section *** (МетМат.Просмотр Get start)

                // *** End programmer edit section *** (МетМат.Просмотр Get start)
                IIS.Kursovaya_Rabota_4.Просмотр result = this.fПросмотр;
                // *** Start programmer edit section *** (МетМат.Просмотр Get end)

                // *** End programmer edit section *** (МетМат.Просмотр Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (МетМат.Просмотр Set start)

                // *** End programmer edit section *** (МетМат.Просмотр Set start)
                this.fПросмотр = value;
                // *** Start programmer edit section *** (МетМат.Просмотр Set end)

                // *** End programmer edit section *** (МетМат.Просмотр Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "МетМатE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View МетМатE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("МетМатE", typeof(IIS.Kursovaya_Rabota_4.МетМат));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of МетМат.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfМетМат CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfМетМат CustomAttributes)
    public class DetailArrayOfМетМат : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Kursovaya_Rabota_4.DetailArrayOfМетМат members)

        // *** End programmer edit section *** (IIS.Kursovaya_Rabota_4.DetailArrayOfМетМат members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type МетМат by index.
        /// </summary>
        /// <summary>
        /// Adds object with type МетМат.
        /// </summary>
        public DetailArrayOfМетМат(IIS.Kursovaya_Rabota_4.Просмотр fПросмотр) : 
                base(typeof(МетМат), ((ICSSoft.STORMNET.DataObject)(fПросмотр)))
        {
        }
        
        public IIS.Kursovaya_Rabota_4.МетМат this[int index]
        {
            get
            {
                return ((IIS.Kursovaya_Rabota_4.МетМат)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Kursovaya_Rabota_4.МетМат dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
