//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kursovaya_Rabota_4
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Просмотр.
    /// </summary>
    // *** Start programmer edit section *** (Просмотр CustomAttributes)

    // *** End programmer edit section *** (Просмотр CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПросмотрE", new string[] {
            "СпрСтуд as \'Фио студента\'",
            "СпрСтуд.Фио as \'Фио студента\'",
            "СпрСтуд.СпрГруппа.Назв as \'Группа\'"})]
    [AssociatedDetailViewAttribute("ПросмотрE", "МетМат", "МетМатE", true, "", "Просмотр прикрепленных книг студентом", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("ПросмотрE", "СпрСтуд", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Фио студента")]
    [View("ПросмотрL", new string[] {
            "СпрСтуд.Фио as \'Фио студента\'",
            "СпрСтуд.СпрГруппа.Назв as \'Группа\'"})]
    public class Просмотр : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДата;
        
        private IIS.Kursovaya_Rabota_4.СпрСтуд fСпрСтуд;
        
        private IIS.Kursovaya_Rabota_4.DetailArrayOfМетМат fМетМат;
        
        // *** Start programmer edit section *** (Просмотр CustomMembers)

        // *** End programmer edit section *** (Просмотр CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (Просмотр.Дата CustomAttributes)

        // *** End programmer edit section *** (Просмотр.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (Просмотр.Дата Get start)

                // *** End programmer edit section *** (Просмотр.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (Просмотр.Дата Get end)

                // *** End programmer edit section *** (Просмотр.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Просмотр.Дата Set start)

                // *** End programmer edit section *** (Просмотр.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (Просмотр.Дата Set end)

                // *** End programmer edit section *** (Просмотр.Дата Set end)
            }
        }
        
        /// <summary>
        /// Просмотр.
        /// </summary>
        // *** Start programmer edit section *** (Просмотр.СпрСтуд CustomAttributes)

        // *** End programmer edit section *** (Просмотр.СпрСтуд CustomAttributes)
        [PropertyStorage(new string[] {
                "СпрСтуд"})]
        [NotNull()]
        public virtual IIS.Kursovaya_Rabota_4.СпрСтуд СпрСтуд
        {
            get
            {
                // *** Start programmer edit section *** (Просмотр.СпрСтуд Get start)

                // *** End programmer edit section *** (Просмотр.СпрСтуд Get start)
                IIS.Kursovaya_Rabota_4.СпрСтуд result = this.fСпрСтуд;
                // *** Start programmer edit section *** (Просмотр.СпрСтуд Get end)

                // *** End programmer edit section *** (Просмотр.СпрСтуд Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Просмотр.СпрСтуд Set start)

                // *** End programmer edit section *** (Просмотр.СпрСтуд Set start)
                this.fСпрСтуд = value;
                // *** Start programmer edit section *** (Просмотр.СпрСтуд Set end)

                // *** End programmer edit section *** (Просмотр.СпрСтуд Set end)
            }
        }
        
        /// <summary>
        /// Просмотр.
        /// </summary>
        // *** Start programmer edit section *** (Просмотр.МетМат CustomAttributes)

        // *** End programmer edit section *** (Просмотр.МетМат CustomAttributes)
        public virtual IIS.Kursovaya_Rabota_4.DetailArrayOfМетМат МетМат
        {
            get
            {
                // *** Start programmer edit section *** (Просмотр.МетМат Get start)

                // *** End programmer edit section *** (Просмотр.МетМат Get start)
                if ((this.fМетМат == null))
                {
                    this.fМетМат = new IIS.Kursovaya_Rabota_4.DetailArrayOfМетМат(this);
                }
                IIS.Kursovaya_Rabota_4.DetailArrayOfМетМат result = this.fМетМат;
                // *** Start programmer edit section *** (Просмотр.МетМат Get end)

                // *** End programmer edit section *** (Просмотр.МетМат Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Просмотр.МетМат Set start)

                // *** End programmer edit section *** (Просмотр.МетМат Set start)
                this.fМетМат = value;
                // *** Start programmer edit section *** (Просмотр.МетМат Set end)

                // *** End programmer edit section *** (Просмотр.МетМат Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПросмотрE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПросмотрE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПросмотрE", typeof(IIS.Kursovaya_Rabota_4.Просмотр));
                }
            }
            
            /// <summary>
            /// "ПросмотрL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПросмотрL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПросмотрL", typeof(IIS.Kursovaya_Rabota_4.Просмотр));
                }
            }
        }
    }
}
