//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kursovaya_Rabota_4
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Должность.
    /// </summary>
    // *** Start programmer edit section *** (СпрДолжность CustomAttributes)

    // *** End programmer edit section *** (СпрДолжность CustomAttributes)
    [AutoAltered()]
    [Caption("Справочник Должности")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СпрДолжностьE", new string[] {
            "Наименование as \'Должность\'"})]
    [View("СпрДолжностьL", new string[] {
            "Наименование as \'Должность\'"})]
    public class СпрДолжность : ICSSoft.STORMNET.DataObject
    {
        
        private string fНаименование;
        
        // *** Start programmer edit section *** (СпрДолжность CustomMembers)

        // *** End programmer edit section *** (СпрДолжность CustomMembers)

        
        /// <summary>
        /// Наименование.
        /// </summary>
        // *** Start programmer edit section *** (СпрДолжность.Наименование CustomAttributes)

        // *** End programmer edit section *** (СпрДолжность.Наименование CustomAttributes)
        [StrLen(255)]
        public virtual string Наименование
        {
            get
            {
                // *** Start programmer edit section *** (СпрДолжность.Наименование Get start)

                // *** End programmer edit section *** (СпрДолжность.Наименование Get start)
                string result = this.fНаименование;
                // *** Start programmer edit section *** (СпрДолжность.Наименование Get end)

                // *** End programmer edit section *** (СпрДолжность.Наименование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СпрДолжность.Наименование Set start)

                // *** End programmer edit section *** (СпрДолжность.Наименование Set start)
                this.fНаименование = value;
                // *** Start programmer edit section *** (СпрДолжность.Наименование Set end)

                // *** End programmer edit section *** (СпрДолжность.Наименование Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СпрДолжностьE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СпрДолжностьE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СпрДолжностьE", typeof(IIS.Kursovaya_Rabota_4.СпрДолжность));
                }
            }
            
            /// <summary>
            /// "СпрДолжностьL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СпрДолжностьL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СпрДолжностьL", typeof(IIS.Kursovaya_Rabota_4.СпрДолжность));
                }
            }
        }
    }
}
