//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kursovaya_Rabota_4
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// СпрМатериалы.
    /// </summary>
    // *** Start programmer edit section *** (СпрМатериалы CustomAttributes)

    // *** End programmer edit section *** (СпрМатериалы CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СпрМатериалыE", new string[] {
            "Наименование as \'Название материала\'",
            "Вид as \'Вид материала\'",
            "СпрДисциплина as \'Дисциплина\'",
            "СпрДисциплина.Наименование as \'Дисциплина\'"})]
    [View("СпрМатериалыL", new string[] {
            "Наименование as \'Название материала\'",
            "Вид as \'Вид материала\'",
            "СпрДисциплина.Наименование as \'Дисциплина\'"})]
    public class СпрМатериалы : ICSSoft.STORMNET.DataObject
    {
        
        private string fНаименование;
        
        private IIS.Kursovaya_Rabota_4.Вид fВид;
        
        private IIS.Kursovaya_Rabota_4.СпрДисциплина fСпрДисциплина;
        
        // *** Start programmer edit section *** (СпрМатериалы CustomMembers)

        // *** End programmer edit section *** (СпрМатериалы CustomMembers)

        
        /// <summary>
        /// Вид.
        /// </summary>
        // *** Start programmer edit section *** (СпрМатериалы.Вид CustomAttributes)

        // *** End programmer edit section *** (СпрМатериалы.Вид CustomAttributes)
        public virtual IIS.Kursovaya_Rabota_4.Вид Вид
        {
            get
            {
                // *** Start programmer edit section *** (СпрМатериалы.Вид Get start)

                // *** End programmer edit section *** (СпрМатериалы.Вид Get start)
                IIS.Kursovaya_Rabota_4.Вид result = this.fВид;
                // *** Start programmer edit section *** (СпрМатериалы.Вид Get end)

                // *** End programmer edit section *** (СпрМатериалы.Вид Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СпрМатериалы.Вид Set start)

                // *** End programmer edit section *** (СпрМатериалы.Вид Set start)
                this.fВид = value;
                // *** Start programmer edit section *** (СпрМатериалы.Вид Set end)

                // *** End programmer edit section *** (СпрМатериалы.Вид Set end)
            }
        }
        
        /// <summary>
        /// Наименование.
        /// </summary>
        // *** Start programmer edit section *** (СпрМатериалы.Наименование CustomAttributes)

        // *** End programmer edit section *** (СпрМатериалы.Наименование CustomAttributes)
        [StrLen(255)]
        public virtual string Наименование
        {
            get
            {
                // *** Start programmer edit section *** (СпрМатериалы.Наименование Get start)

                // *** End programmer edit section *** (СпрМатериалы.Наименование Get start)
                string result = this.fНаименование;
                // *** Start programmer edit section *** (СпрМатериалы.Наименование Get end)

                // *** End programmer edit section *** (СпрМатериалы.Наименование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СпрМатериалы.Наименование Set start)

                // *** End programmer edit section *** (СпрМатериалы.Наименование Set start)
                this.fНаименование = value;
                // *** Start programmer edit section *** (СпрМатериалы.Наименование Set end)

                // *** End programmer edit section *** (СпрМатериалы.Наименование Set end)
            }
        }
        
        /// <summary>
        /// СпрМатериалы.
        /// </summary>
        // *** Start programmer edit section *** (СпрМатериалы.СпрДисциплина CustomAttributes)

        // *** End programmer edit section *** (СпрМатериалы.СпрДисциплина CustomAttributes)
        [PropertyStorage(new string[] {
                "СпрДисциплина"})]
        [NotNull()]
        public virtual IIS.Kursovaya_Rabota_4.СпрДисциплина СпрДисциплина
        {
            get
            {
                // *** Start programmer edit section *** (СпрМатериалы.СпрДисциплина Get start)

                // *** End programmer edit section *** (СпрМатериалы.СпрДисциплина Get start)
                IIS.Kursovaya_Rabota_4.СпрДисциплина result = this.fСпрДисциплина;
                // *** Start programmer edit section *** (СпрМатериалы.СпрДисциплина Get end)

                // *** End programmer edit section *** (СпрМатериалы.СпрДисциплина Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СпрМатериалы.СпрДисциплина Set start)

                // *** End programmer edit section *** (СпрМатериалы.СпрДисциплина Set start)
                this.fСпрДисциплина = value;
                // *** Start programmer edit section *** (СпрМатериалы.СпрДисциплина Set end)

                // *** End programmer edit section *** (СпрМатериалы.СпрДисциплина Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СпрМатериалыE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СпрМатериалыE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СпрМатериалыE", typeof(IIS.Kursovaya_Rabota_4.СпрМатериалы));
                }
            }
            
            /// <summary>
            /// "СпрМатериалыL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СпрМатериалыL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СпрМатериалыL", typeof(IIS.Kursovaya_Rabota_4.СпрМатериалы));
                }
            }
        }
    }
}
