//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kursovaya_Rabota_4
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Спр препод.
    /// </summary>
    // *** Start programmer edit section *** (СпрПрепод CustomAttributes)

    // *** End programmer edit section *** (СпрПрепод CustomAttributes)
    [AutoAltered()]
    [Caption("Справочник преподаватели")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СпрПреподE", new string[] {
            "Фио as \'Фио преподавателя\'",
            "СпрДолжность as \'Должность\'",
            "СпрДолжность.Наименование as \'Должность\'",
            "СпрГруппа as \'Группа\'",
            "СпрГруппа.Назв as \'Группа\'",
            "СпрДисциплина as \'Дисциплина\'",
            "СпрДисциплина.Наименование as \'Дисциплина\'"})]
    [View("СпрПреподL", new string[] {
            "Фио as \'Фио преподавателя\'",
            "СпрДолжность.Наименование as \'Должность\'",
            "СпрГруппа.Назв as \'Группа\'",
            "СпрДисциплина.Наименование as \'Дисциплина\'"})]
    public class СпрПрепод : ICSSoft.STORMNET.DataObject
    {
        
        private string fФио;
        
        private IIS.Kursovaya_Rabota_4.СпрГруппа fСпрГруппа;
        
        private IIS.Kursovaya_Rabota_4.СпрДисциплина fСпрДисциплина;
        
        private IIS.Kursovaya_Rabota_4.СпрДолжность fСпрДолжность;
        
        // *** Start programmer edit section *** (СпрПрепод CustomMembers)

        // *** End programmer edit section *** (СпрПрепод CustomMembers)

        
        /// <summary>
        /// Фио.
        /// </summary>
        // *** Start programmer edit section *** (СпрПрепод.Фио CustomAttributes)

        // *** End programmer edit section *** (СпрПрепод.Фио CustomAttributes)
        [StrLen(255)]
        public virtual string Фио
        {
            get
            {
                // *** Start programmer edit section *** (СпрПрепод.Фио Get start)

                // *** End programmer edit section *** (СпрПрепод.Фио Get start)
                string result = this.fФио;
                // *** Start programmer edit section *** (СпрПрепод.Фио Get end)

                // *** End programmer edit section *** (СпрПрепод.Фио Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СпрПрепод.Фио Set start)

                // *** End programmer edit section *** (СпрПрепод.Фио Set start)
                this.fФио = value;
                // *** Start programmer edit section *** (СпрПрепод.Фио Set end)

                // *** End programmer edit section *** (СпрПрепод.Фио Set end)
            }
        }
        
        /// <summary>
        /// Спр препод.
        /// </summary>
        // *** Start programmer edit section *** (СпрПрепод.СпрГруппа CustomAttributes)

        // *** End programmer edit section *** (СпрПрепод.СпрГруппа CustomAttributes)
        [PropertyStorage(new string[] {
                "СпрГруппа"})]
        [NotNull()]
        public virtual IIS.Kursovaya_Rabota_4.СпрГруппа СпрГруппа
        {
            get
            {
                // *** Start programmer edit section *** (СпрПрепод.СпрГруппа Get start)

                // *** End programmer edit section *** (СпрПрепод.СпрГруппа Get start)
                IIS.Kursovaya_Rabota_4.СпрГруппа result = this.fСпрГруппа;
                // *** Start programmer edit section *** (СпрПрепод.СпрГруппа Get end)

                // *** End programmer edit section *** (СпрПрепод.СпрГруппа Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СпрПрепод.СпрГруппа Set start)

                // *** End programmer edit section *** (СпрПрепод.СпрГруппа Set start)
                this.fСпрГруппа = value;
                // *** Start programmer edit section *** (СпрПрепод.СпрГруппа Set end)

                // *** End programmer edit section *** (СпрПрепод.СпрГруппа Set end)
            }
        }
        
        /// <summary>
        /// Спр препод.
        /// </summary>
        // *** Start programmer edit section *** (СпрПрепод.СпрДисциплина CustomAttributes)

        // *** End programmer edit section *** (СпрПрепод.СпрДисциплина CustomAttributes)
        [PropertyStorage(new string[] {
                "СпрДисциплина"})]
        [NotNull()]
        public virtual IIS.Kursovaya_Rabota_4.СпрДисциплина СпрДисциплина
        {
            get
            {
                // *** Start programmer edit section *** (СпрПрепод.СпрДисциплина Get start)

                // *** End programmer edit section *** (СпрПрепод.СпрДисциплина Get start)
                IIS.Kursovaya_Rabota_4.СпрДисциплина result = this.fСпрДисциплина;
                // *** Start programmer edit section *** (СпрПрепод.СпрДисциплина Get end)

                // *** End programmer edit section *** (СпрПрепод.СпрДисциплина Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СпрПрепод.СпрДисциплина Set start)

                // *** End programmer edit section *** (СпрПрепод.СпрДисциплина Set start)
                this.fСпрДисциплина = value;
                // *** Start programmer edit section *** (СпрПрепод.СпрДисциплина Set end)

                // *** End programmer edit section *** (СпрПрепод.СпрДисциплина Set end)
            }
        }
        
        /// <summary>
        /// Спр препод.
        /// </summary>
        // *** Start programmer edit section *** (СпрПрепод.СпрДолжность CustomAttributes)

        // *** End programmer edit section *** (СпрПрепод.СпрДолжность CustomAttributes)
        [PropertyStorage(new string[] {
                "СпрДолжность"})]
        [NotNull()]
        public virtual IIS.Kursovaya_Rabota_4.СпрДолжность СпрДолжность
        {
            get
            {
                // *** Start programmer edit section *** (СпрПрепод.СпрДолжность Get start)

                // *** End programmer edit section *** (СпрПрепод.СпрДолжность Get start)
                IIS.Kursovaya_Rabota_4.СпрДолжность result = this.fСпрДолжность;
                // *** Start programmer edit section *** (СпрПрепод.СпрДолжность Get end)

                // *** End programmer edit section *** (СпрПрепод.СпрДолжность Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СпрПрепод.СпрДолжность Set start)

                // *** End programmer edit section *** (СпрПрепод.СпрДолжность Set start)
                this.fСпрДолжность = value;
                // *** Start programmer edit section *** (СпрПрепод.СпрДолжность Set end)

                // *** End programmer edit section *** (СпрПрепод.СпрДолжность Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СпрПреподE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СпрПреподE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СпрПреподE", typeof(IIS.Kursovaya_Rabota_4.СпрПрепод));
                }
            }
            
            /// <summary>
            /// "СпрПреподL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СпрПреподL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СпрПреподL", typeof(IIS.Kursovaya_Rabota_4.СпрПрепод));
                }
            }
        }
    }
}
