//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kursovaya_Rabota_4
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Спр группа.
    /// </summary>
    // *** Start programmer edit section *** (СпрГруппа CustomAttributes)

    // *** End programmer edit section *** (СпрГруппа CustomAttributes)
    [AutoAltered()]
    [Caption("Справочник группы")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СпрГруппаE", new string[] {
            "Назв as \'Наименование группы\'"})]
    [View("СпрГруппаL", new string[] {
            "Назв as \'Наименование группы\'"})]
    public class СпрГруппа : ICSSoft.STORMNET.DataObject
    {
        
        private string fНазв;
        
        // *** Start programmer edit section *** (СпрГруппа CustomMembers)

        // *** End programmer edit section *** (СпрГруппа CustomMembers)

        
        /// <summary>
        /// Назв.
        /// </summary>
        // *** Start programmer edit section *** (СпрГруппа.Назв CustomAttributes)

        // *** End programmer edit section *** (СпрГруппа.Назв CustomAttributes)
        [StrLen(255)]
        public virtual string Назв
        {
            get
            {
                // *** Start programmer edit section *** (СпрГруппа.Назв Get start)

                // *** End programmer edit section *** (СпрГруппа.Назв Get start)
                string result = this.fНазв;
                // *** Start programmer edit section *** (СпрГруппа.Назв Get end)

                // *** End programmer edit section *** (СпрГруппа.Назв Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СпрГруппа.Назв Set start)

                // *** End programmer edit section *** (СпрГруппа.Назв Set start)
                this.fНазв = value;
                // *** Start programmer edit section *** (СпрГруппа.Назв Set end)

                // *** End programmer edit section *** (СпрГруппа.Назв Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СпрГруппаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СпрГруппаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СпрГруппаE", typeof(IIS.Kursovaya_Rabota_4.СпрГруппа));
                }
            }
            
            /// <summary>
            /// "СпрГруппаL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СпрГруппаL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СпрГруппаL", typeof(IIS.Kursovaya_Rabota_4.СпрГруппа));
                }
            }
        }
    }
}
