//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kursovaya_Rabota_4
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Спр дисциплина.
    /// </summary>
    // *** Start programmer edit section *** (СпрДисциплина CustomAttributes)

    // *** End programmer edit section *** (СпрДисциплина CustomAttributes)
    [AutoAltered()]
    [Caption("Справочник дисциплины")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СпрДисциплинаE", new string[] {
            "Наименование as \'Наименование Дисциплины\'"})]
    [View("СпрДисциплинаL", new string[] {
            "Наименование as \'Наименование Дисциплины\'"})]
    public class СпрДисциплина : ICSSoft.STORMNET.DataObject
    {
        
        private string fНаименование;
        
        // *** Start programmer edit section *** (СпрДисциплина CustomMembers)

        // *** End programmer edit section *** (СпрДисциплина CustomMembers)

        
        /// <summary>
        /// Наименование.
        /// </summary>
        // *** Start programmer edit section *** (СпрДисциплина.Наименование CustomAttributes)

        // *** End programmer edit section *** (СпрДисциплина.Наименование CustomAttributes)
        [StrLen(255)]
        public virtual string Наименование
        {
            get
            {
                // *** Start programmer edit section *** (СпрДисциплина.Наименование Get start)

                // *** End programmer edit section *** (СпрДисциплина.Наименование Get start)
                string result = this.fНаименование;
                // *** Start programmer edit section *** (СпрДисциплина.Наименование Get end)

                // *** End programmer edit section *** (СпрДисциплина.Наименование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СпрДисциплина.Наименование Set start)

                // *** End programmer edit section *** (СпрДисциплина.Наименование Set start)
                this.fНаименование = value;
                // *** Start programmer edit section *** (СпрДисциплина.Наименование Set end)

                // *** End programmer edit section *** (СпрДисциплина.Наименование Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СпрДисциплинаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СпрДисциплинаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СпрДисциплинаE", typeof(IIS.Kursovaya_Rabota_4.СпрДисциплина));
                }
            }
            
            /// <summary>
            /// "СпрДисциплинаL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СпрДисциплинаL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СпрДисциплинаL", typeof(IIS.Kursovaya_Rabota_4.СпрДисциплина));
                }
            }
        }
    }
}
