//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kursovaya_Rabota_4
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Статус.
    /// </summary>
    // *** Start programmer edit section *** (Статус CustomAttributes)

    // *** End programmer edit section *** (Статус CustomAttributes)
    public enum Статус
    {
        
        // *** Start programmer edit section *** (Статус.Прикреплён CustomAttributes)

        // *** End programmer edit section *** (Статус.Прикреплён CustomAttributes)
        Прикреплён,
        
        // *** Start programmer edit section *** (Статус.НеПрикреплён CustomAttributes)

        // *** End programmer edit section *** (Статус.НеПрикреплён CustomAttributes)
        НеПрикреплён,
    }
}
