//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kursovaya_Rabota_4
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Стат.
    /// </summary>
    // *** Start programmer edit section *** (Стат CustomAttributes)

    // *** End programmer edit section *** (Стат CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СтатE", new string[] {
            "СпрПрепод as \'Фио преподавателя\'",
            "СпрПрепод.Фио as \'Фио преподавателя\'",
            "СпрПрепод.СпрДолжность.Наименование as \'Должность\'",
            "СпрПрепод.СпрДисциплина.Наименование as \'Дисциплина\'",
            "СпрПрепод.СпрГруппа.Назв as \'Группа\'"})]
    [AssociatedDetailViewAttribute("СтатE", "Контр", "КонтрE", true, "", "Функция: Контроль просмотра и прикрепления студентов", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("СтатE", "СпрПрепод", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Фио преподавателя")]
    [View("СтатL", new string[] {
            "СпрПрепод.Фио as \'Фио преподавателя\'",
            "СпрПрепод.СпрДолжность.Наименование as \'Должность\'",
            "СпрПрепод.СпрДисциплина.Наименование as \'Дисциплина\'",
            "СпрПрепод.СпрГруппа.Назв as \'Группа\'"})]
    public class Стат : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДата;
        
        private IIS.Kursovaya_Rabota_4.СпрПрепод fСпрПрепод;
        
        private IIS.Kursovaya_Rabota_4.СпрСтуд fСпрСтуд;
        
        private IIS.Kursovaya_Rabota_4.DetailArrayOfКонтр fКонтр;
        
        // *** Start programmer edit section *** (Стат CustomMembers)

        // *** End programmer edit section *** (Стат CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (Стат.Дата CustomAttributes)

        // *** End programmer edit section *** (Стат.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (Стат.Дата Get start)

                // *** End programmer edit section *** (Стат.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (Стат.Дата Get end)

                // *** End programmer edit section *** (Стат.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Стат.Дата Set start)

                // *** End programmer edit section *** (Стат.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (Стат.Дата Set end)

                // *** End programmer edit section *** (Стат.Дата Set end)
            }
        }
        
        /// <summary>
        /// Стат.
        /// </summary>
        // *** Start programmer edit section *** (Стат.СпрПрепод CustomAttributes)

        // *** End programmer edit section *** (Стат.СпрПрепод CustomAttributes)
        [PropertyStorage(new string[] {
                "СпрПрепод"})]
        [NotNull()]
        public virtual IIS.Kursovaya_Rabota_4.СпрПрепод СпрПрепод
        {
            get
            {
                // *** Start programmer edit section *** (Стат.СпрПрепод Get start)

                // *** End programmer edit section *** (Стат.СпрПрепод Get start)
                IIS.Kursovaya_Rabota_4.СпрПрепод result = this.fСпрПрепод;
                // *** Start programmer edit section *** (Стат.СпрПрепод Get end)

                // *** End programmer edit section *** (Стат.СпрПрепод Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Стат.СпрПрепод Set start)

                // *** End programmer edit section *** (Стат.СпрПрепод Set start)
                this.fСпрПрепод = value;
                // *** Start programmer edit section *** (Стат.СпрПрепод Set end)

                // *** End programmer edit section *** (Стат.СпрПрепод Set end)
            }
        }
        
        /// <summary>
        /// Стат.
        /// </summary>
        // *** Start programmer edit section *** (Стат.СпрСтуд CustomAttributes)

        // *** End programmer edit section *** (Стат.СпрСтуд CustomAttributes)
        [PropertyStorage(new string[] {
                "СпрСтуд"})]
        [NotNull()]
        public virtual IIS.Kursovaya_Rabota_4.СпрСтуд СпрСтуд
        {
            get
            {
                // *** Start programmer edit section *** (Стат.СпрСтуд Get start)

                // *** End programmer edit section *** (Стат.СпрСтуд Get start)
                IIS.Kursovaya_Rabota_4.СпрСтуд result = this.fСпрСтуд;
                // *** Start programmer edit section *** (Стат.СпрСтуд Get end)

                // *** End programmer edit section *** (Стат.СпрСтуд Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Стат.СпрСтуд Set start)

                // *** End programmer edit section *** (Стат.СпрСтуд Set start)
                this.fСпрСтуд = value;
                // *** Start programmer edit section *** (Стат.СпрСтуд Set end)

                // *** End programmer edit section *** (Стат.СпрСтуд Set end)
            }
        }
        
        /// <summary>
        /// Стат.
        /// </summary>
        // *** Start programmer edit section *** (Стат.Контр CustomAttributes)

        // *** End programmer edit section *** (Стат.Контр CustomAttributes)
        public virtual IIS.Kursovaya_Rabota_4.DetailArrayOfКонтр Контр
        {
            get
            {
                // *** Start programmer edit section *** (Стат.Контр Get start)

                // *** End programmer edit section *** (Стат.Контр Get start)
                if ((this.fКонтр == null))
                {
                    this.fКонтр = new IIS.Kursovaya_Rabota_4.DetailArrayOfКонтр(this);
                }
                IIS.Kursovaya_Rabota_4.DetailArrayOfКонтр result = this.fКонтр;
                // *** Start programmer edit section *** (Стат.Контр Get end)

                // *** End programmer edit section *** (Стат.Контр Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Стат.Контр Set start)

                // *** End programmer edit section *** (Стат.Контр Set start)
                this.fКонтр = value;
                // *** Start programmer edit section *** (Стат.Контр Set end)

                // *** End programmer edit section *** (Стат.Контр Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СтатE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СтатE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СтатE", typeof(IIS.Kursovaya_Rabota_4.Стат));
                }
            }
            
            /// <summary>
            /// "СтатL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СтатL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СтатL", typeof(IIS.Kursovaya_Rabota_4.Стат));
                }
            }
        }
    }
}
