//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kursovaya_Rabota_4
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Статус.
    /// </summary>
    // *** Start programmer edit section *** (Статус CustomAttributes)

    // *** End programmer edit section *** (Статус CustomAttributes)
    public enum Статус
    {
        
        // *** Start programmer edit section *** (Статус.НеПрикрепл CustomAttributes)

        // *** End programmer edit section *** (Статус.НеПрикрепл CustomAttributes)
        [Caption("Не прикреплён")]
        НеПрикрепл,
        
        // *** Start programmer edit section *** (Статус.Прикрепл CustomAttributes)

        // *** End programmer edit section *** (Статус.Прикрепл CustomAttributes)
        [Caption("Прикреплён")]
        Прикрепл,
    }
}
